import{addDoc,collection,deleteDoc,doc,documentId,getDocs,limit,orderBy,query,serverTimestamp,setDoc,updateDoc,where,writeBatch}from'firebase/firestore';import{db}from'../lib/firebase';
const stamp=v=>({...v,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
export async function loadUserData(uid){const memberSnap=await getDocs(query(collection(db,'fundMembers'),where('userId','==',uid)));const memberships=memberSnap.docs.map(d=>({id:d.id,...d.data()})),ids=memberships.map(x=>x.fundId);const funds=[];for(let i=0;i<ids.length;i+=10){const s=await getDocs(query(collection(db,'funds'),where(documentId(),'in',ids.slice(i,i+10))));funds.push(...s.docs.map(d=>({id:d.id,...d.data()})))}const owned=await getDocs(query(collection(db,'remittances'),where('ownerId','==',uid),limit(150)));const remittances=owned.docs.map(d=>({id:d.id,...d.data()}));const allocations=[],transactions=[];for(let i=0;i<ids.length;i+=10){const chunk=ids.slice(i,i+10);const[a,t]=await Promise.all([getDocs(query(collection(db,'allocations'),where('fundId','in',chunk),limit(300))),getDocs(query(collection(db,'transactions'),where('fundId','in',chunk),orderBy('date','desc'),limit(300)))]);allocations.push(...a.docs.map(d=>({id:d.id,...d.data()})));transactions.push(...t.docs.map(d=>({id:d.id,...d.data()})))}const cats=await getDocs(query(collection(db,'categories'),where('userId','==',uid)));return{funds,memberships,remittances,allocations,transactions,categories:cats.docs.map(d=>({id:d.id,...d.data()}))}}
export async function createFund(uid,data){const ref=doc(collection(db,'funds')),batch=writeBatch(db);batch.set(ref,stamp({...data,ownerId:uid,archived:false}));batch.set(doc(db,'fundMembers',`${ref.id}_${uid}`),{fundId:ref.id,userId:uid,role:'owner',createdAt:serverTimestamp()});await batch.commit();return ref.id}
export const updateFund=(id,data)=>updateDoc(doc(db,'funds',id),{...data,updatedAt:serverTimestamp()});
export const addTransaction=(uid,data)=>addDoc(collection(db,'transactions'),stamp({...data,userId:uid}));
export const updateTransaction=(id,data)=>updateDoc(doc(db,'transactions',id),{...data,updatedAt:serverTimestamp()});
export const removeTransaction=id=>deleteDoc(doc(db,'transactions',id));
export async function createTransfer(uid,fromId,toId,amount,date,note){const batch=writeBatch(db),linkId=doc(collection(db,'transactions')).id;for(const [fundId,value]of[[fromId,-amount],[toId,amount]])batch.set(doc(collection(db,'transactions')),stamp({fundId,userId:uid,type:'transfer',amount:value,description:`Transfer ${value<0?'to':'from'} fund`,date,note,linkId}));await batch.commit()}
export async function createRemittance(uid,data,allocations){const batch=writeBatch(db),ref=doc(collection(db,'remittances'));batch.set(ref,stamp({...data,ownerId:uid,currency:'PKR'}));allocations.filter(a=>a.amount>0).forEach(a=>batch.set(doc(collection(db,'allocations')),{remittanceId:ref.id,fundId:a.fundId,amount:Number(a.amount),createdAt:serverTimestamp()}));await batch.commit()}
export const addAllocation=data=>addDoc(collection(db,'allocations'),{...data,createdAt:serverTimestamp()});
export const addCategory=(uid,name,symbol='◆')=>addDoc(collection(db,'categories'),{userId:uid,name,symbol,createdAt:serverTimestamp()});
export async function addMember(fundId,email,role){const s=await getDocs(query(collection(db,'users'),where('email','==',email.toLowerCase()),limit(1)));if(s.empty)throw Error('No registered user found with that email.');const user=s.docs[0];await setDoc(doc(db,'fundMembers',`${fundId}_${user.id}`),{fundId,userId:user.id,displayName:user.data().displayName,email:user.data().email,role,createdAt:serverTimestamp()})}
export const updateMember=(id,role)=>updateDoc(doc(db,'fundMembers',id),{role});export const removeMember=id=>deleteDoc(doc(db,'fundMembers',id));
